# Generated by Django 4.0.2 on 2022-03-04 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_doctor_id_alter_expertize_id_alter_faq_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 4, 10, 44, 29, 492557, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
