# Generated by Django 4.0.2 on 2022-03-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_history', models.TextField()),
                ('consultation_text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='consultation_text',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='user',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.consultation'),
        ),
    ]
