# Generated by Django 4.0.2 on 2022-03-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consultation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Approved'),
        ),
    ]
