# Generated by Django 3.2 on 2022-03-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220305_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consultation',
        ),
        migrations.AddField(
            model_name='user',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.consultation'),
        ),
    ]
