# Generated by Django 3.2 on 2022-03-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220305_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_text',
            field=models.TextField(verbose_name='consultation_text'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medical_history',
            field=models.TextField(verbose_name='medical_history'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(error_messages={'Negative integer': 'Please enter a Valid age'}, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that phone number already exists.'}, max_length=20, null=True, unique=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(error_messages={'required': 'Role must be provided'}, max_length=12, verbose_name='role'),
        ),
    ]
