# Generated by Django 3.2 on 2022-03-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20220311_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medical_history',
            field=models.TextField(),
        ),
    ]
