# Generated by Django 4.0.2 on 2022-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_consultation_remove_user_consultation_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='reply',
            field=models.TextField(null=True),
        ),
    ]
