# Generated by Django 3.2 on 2022-03-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_consultation_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.consultation'),
        ),
    ]
