# Generated by Django 3.2 on 2022-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_consultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consultation',
        ),
        migrations.AddField(
            model_name='user',
            name='consultation',
            field=models.ManyToManyField(related_name='user', to='accounts.Consultation'),
        ),
    ]
