# Generated by Django 4.0.2 on 2022-03-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(error_messages={'Negative integer': 'Please enter a Valid age'}, null=True, verbose_name='age')),
                ('chest_pain_type', models.CharField(choices=[('asympt', 'Asympt'), ('atyp_angina', 'Atyp_angina'), ('non_anginal', 'Non_anginal')], default='', max_length=20, null=True, verbose_name='chest pain')),
                ('rest_electro', models.CharField(choices=[('normal', 'Normal'), ('left_vent_hyper', 'Left_vent_hyper'), ('st_t_wave_abnormality', 'St_t_wave_abnormality')], default='', max_length=22, null=True, verbose_name='rest electro')),
                ('rest_blood_pressure', models.PositiveIntegerField(error_messages={'Negative integer': 'Please enter a Valid age'}, null=True, verbose_name='rest blood pressure')),
                ('max_heart_rate', models.PositiveIntegerField(error_messages={'Negative integer': 'Please enter a Valid age'}, null=True, verbose_name='max heart rate')),
                ('blood_sugar', models.BooleanField(blank=True, default=False, verbose_name='blood sugar')),
                ('exercice_angina', models.BooleanField(blank=True, default=False, verbose_name='exercice angina')),
            ],
        ),
    ]
